### ISSUE TITLE
Создание элемента просмотра файлов

### ISSUE THREAD

**Issue by CyberMonster** [MTKPMP12-13/Dynamically-linked-archiving-methods#4]
Need transform treeview control. Automatic generation HierarchicalDataTemplate.
&ltpre>XAML:
&ltTreeView x:Name="treeView" Height="160" Canvas.Left="160" Width="357" Canvas.Top="24" ItemsSource="{Binding Elements}">
            &ltTreeView.ItemTemplate>
                &ltHierarchicalDataTemplate DataType="{x:Type Elements}" ItemsSource="{Binding Elements}">
                    &ltTextBlock Text="{Binding Name}"/>
                &lt/HierarchicalDataTemplate>
            &lt/TreeView.ItemTemplate>
        &lt/TreeView>

C#:
namespace Dynamically_linked_archiving_methods
{
    /// &ltsummary>
    /// Логика взаимодействия для MainWindow.xaml
    /// &lt/summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            Elementbase root = new Elementbase("Мой компьютер");
            DataContext = root;
            this.textBox.Text = System.IO.Directory.GetCurrentDirectory();
            this.treeView.Items.Add(root);
        }

```
    /// &ltsummary>
    /// В treeView запишится путь к файлу, если перетянут файл
    /// &lt/summary>
    /// &ltparam name="sender"></param>
    /// &ltparam name="e"></param>
    private void listView_Drop(object sender, DragEventArgs e)
    {
        if (e.Data.GetDataPresent(System.Windows.DataFormats.FileDrop))
        {
            foreach (string x in (string[])e.Data.GetData(System.Windows.DataFormats.FileDrop))
            {
                if (this.listView.Items.IndexOf(x) == -1)
                    this.listView.Items.Add(x);
            }
        }
    }
    public class Elementbase
    {
        public Elementbase(string Name, string Path, ObservableCollection<Elementbase> Elements)
        {
            this.Name = Name;
            this.Path = Path;
            this.Elements = Elements;
        }
        public Elementbase(string Name, string Path)
        {
            this.Name = Name;
            this.Path = Path;
        }
        public Elementbase(string Path)
        {
            this.Path = Path;
            this.Name = string.Concat(Path.Reverse().TakeWhile(x => x != System.IO.Path.DirectorySeparatorChar).Reverse());
        }
        public string Name
        {
            get;
            set;
        }
        public string Path
        {
            get;
            set;
        }
        public ObservableCollection<Elementbase> Elements
        {
            get;
            set;
        }
    }
    class MyDataContext
    {
        public MyDataContext()
        {
            Elements = new ObservableCollection<Elementbase>();
            Elements.Add(new Elementbase(System.IO.Directory.GetCurrentDirectory()));
            Elements.Add(new Elementbase(System.IO.Directory.GetCurrentDirectory()));
        }
        public ObservableCollection<Elementbase> Elements
        {
            get;
            set;
        }
    }
}
```

}

**Comment by smokecristall** [comment]
http://www.itshop.ru/Poshagovoe-rukovodstvo-Postroenie-prostogo-prilozheniya-WPF-s-pomoshhyu-konstruktora-WPF/l9i29625
